#include QMK_KEYBOARD_H
#include "sendstring_german.h"

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

 // Turm off Power LEDS
void keyboard_pre_init_user(void) {
  // Set our LED pin as output
  setPinOutput(24);
  // Turn the LED off
  // (Due to technical reasons, high is off and low is on)
  writePinHigh(24);
}

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

	[0] = LAYOUT(	KC_ESC, KC_1, KC_2, KC_3, KC_4, KC_5, 						KC_6, KC_7, KC_8, KC_9, TG(1), KC_BSPC, 
					KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, 						DE_Z, KC_U, KC_I, KC_O, KC_P, DE_UDIA, 
					MO(3), KC_A, KC_S, KC_D, KC_F, KC_G, 						KC_H, KC_J, KC_K, KC_L, MO(3), KC_ENT,
					KC_LCTL, DE_Y, KC_X, KC_C, KC_V, KC_B, KC_LBRC, 	KC_RBRC,KC_N, KC_M, KC_COMM, KC_DOT, DE_ADIA, DE_ODIA, 
					MO(2), KC_LGUI, KC_LALT, KC_SPC, 					KC_LSFT, MO(2), KC_ENT, KC_LCTL),

	[1] = LAYOUT(	_______, _______, _______, _______, _______, _______, 							_______, _______, _______, _______, TG(1), _______, 
					_______, _______, _______, _______, _______, _______,							_______, _______, _______, _______, _______, _______,
					_______, _______, _______, _______, _______, _______, 							_______, _______, _______, _______, _______, _______,
					_______, _______, _______, _______, _______, _______, 	_______,	_______,	_______, _______, _______, _______, _______, _______, 
							 		  _______, _______, _______, _______, 							_______, _______, _______, _______),

	[2] = LAYOUT(	_______, _______, _______, _______, _______, _______, 							_______, _______, _______, _______, _______, _______, 
					_______, _______, KC_BSPC, KC_UP, KC_DELETE, _______,							_______, KC_1, KC_2, KC_3, _______, _______, 
					_______, KC_HOME, KC_LEFT, KC_DOWN, KC_RIGHT, KC_END, 							_______, KC_4, KC_5, KC_6, _______, _______,
					_______, KC_LSFT,   DE_SS, DE_SS, KC_ESC, _______, 	_______,	_______,	_______, KC_7, KC_8, KC_9, _______, _______, 
							 		  _______, _______, _______, _______, 							_______, KC_0, _______, _______),

	[3] = LAYOUT(	_______, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, 							KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, _______, 
					_______, DE_AT, DE_PLUS, DE_LBRC, DE_RBRC, DE_QUES, 					DE_EXLM, DE_LPRN, DE_RPRN, DE_MINS, DE_PERC, _______, 
					_______, DE_ASTR, DE_AMPR, DE_LCBR, DE_RCBR , DE_CIRC, 					DE_UNDS, DE_DLR, DE_BSLS, DE_EQL, _______, _______,
					_______, DE_HASH, DE_SLSH, DE_SCLN, DE_GRV, DE_DQUO, _______, _______,	DE_QUOT, DE_COLN, DE_LABK, DE_RABK, DE_TILD, _______, 
								_______, _______, _______, _______, 					_______, _______, _______, _______),
};


/* The encoder_update_user is a function.
 * It'll be called by QMK every time you turn the encoder.
 *
 * The index parameter tells you which encoder was turned. If you only have
 * one encoder, the index will always be zero.
 * 
 * The clockwise parameter tells you the direction of the encoder. It'll be
 * true when you turned the encoder clockwise, and false otherwise.
 */
bool encoder_update_user(uint8_t index, bool clockwise) {
  /* With an if statement we can check which encoder was turned. */
  if (index == 0) { /* First encoder: Left */
    /* And with another if statement we can check the direction. */
    if (clockwise) {
      /* This is where the actual magic happens: this bit of code taps on the
         Page Down key. You can do anything QMK allows you to do here.
         You'll want to replace these lines with the things you want your
         encoders to do. */
      tap_code(KC_PGDN);
    } else {
      /* And likewise for the other direction, this time Page Down is pressed. */
      tap_code(KC_PGUP);
    }
  /* You can copy the code and change the index for every encoder you have. Most
     keyboards will only have two, so this piece of code will suffice. */
  } else if (index == 1) { /* Second encoder: Right */
    if (clockwise) {
      tap_code(KC_MS_WH_DOWN);
    } else {
      tap_code(KC_MS_WH_UP);
    }
  }
  return false;
}



