#include QMK_KEYBOARD_H
#include "sendstring_german.h"

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

 // Turm off Power LEDS
void keyboard_pre_init_user(void) {
  // Set our LED pin as output
  setPinOutput(24);
  // Turn the LED off
  // (Due to technical reasons, high is off and low is on)
  writePinHigh(24);
}

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

	[0] = LAYOUT(	KC_ESC, KC_1, KC_2, KC_3, KC_4, KC_5, 						KC_6, KC_7, KC_8, KC_9, KC_0, KC_BSPC, 
					KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, 						DE_Z, KC_U, KC_I, KC_O, KC_P, DE_UDIA, 
					KC_LCTL, KC_A, KC_S, KC_D, KC_F, KC_G, 						KC_H, KC_J, KC_K, KC_L, MO(3), DE_ADIA,
					KC_LSFT, DE_Y, KC_X, KC_C, KC_V, KC_B, KC_LBRC, 	KC_RBRC,KC_N, KC_M, KC_COMM, KC_DOT, MO(4), DE_ODIA, 
					MO(2), KC_LGUI, KC_LALT, KC_SPC, 					KC_ENT, MO(2), KC_BSPC, KC_RGUI),

	[1] = LAYOUT(	_______, _______, _______, _______, _______, _______, 							_______, _______, _______, _______, _______, _______, 
					_______, _______, _______, _______, _______, _______,							_______, _______, _______, _______, _______, _______,
					_______, _______, _______, _______, _______, _______, 							_______, _______, _______, _______, _______, _______,
					_______, _______, _______, _______, _______, _______, 	_______,	_______,	_______, _______, _______, _______, _______, _______, 
							 		  _______, _______, _______, _______, 							_______, _______, _______, _______),

	[2] = LAYOUT(	_______, _______, _______, _______, _______, _______, 							_______, _______, _______, _______, _______, _______, 
					_______, _______, KC_BSPC, KC_UP, KC_DELETE, _______,							_______, KC_1, KC_2, KC_3, _______, _______, 
					_______, KC_HOME, KC_LEFT, KC_DOWN, KC_RIGHT, KC_END, 							_______, KC_4, KC_5, KC_6, _______, _______,
					_______, _______, _______, _______, _______, _______, 	_______,	_______,	_______, KC_7, KC_8, KC_9, _______, _______, 
							 		  _______, _______, _______, _______, 							_______, KC_0, _______, _______),

	[3] = LAYOUT(	_______, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, 							KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, _______, 
					_______, DE_AT, DE_PLUS, DE_LBRC, DE_RBRC, DE_QUES, 					DE_EXLM, DE_LPRN, DE_RPRN, DE_MINS, DE_PERC, _______, 
					_______, DE_ASTR, DE_AMPR, DE_LCBR, DE_RCBR , DE_CIRC, 					DE_UNDS, DE_DLR, DE_BSLS, DE_EQL, _______, _______,
					_______, DE_HASH, DE_SLSH, DE_SCLN, DE_GRV, DE_DQUO, _______, _______,	DE_QUOT, DE_COLN, DE_LABK, DE_RABK, DE_TILD, _______, 
								_______, _______, _______, _______, 					_______, _______, _______, _______),
};

#if defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {

};
#endif // defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)




